# Generated by Django 4.2.16 on 2026-09-15 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltimelineevent',
            name='reviewer_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicaltimelineevent',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sourcedocument',
            name='file',
            field=models.FileField(blank=True, upload_to='documents/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='reviewer_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('paralegal', 'Paralegal'), ('attorney', 'Attorney'), ('admin', 'Admin')], default='paralegal', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
