# Generated by Django 4.2.16 on 2026-09-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_case_reviewed_at_case_reviewed_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltimelineevent',
            name='source_document',
        ),
        migrations.RemoveField(
            model_name='timelineevent',
            name='source_document',
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='source_documents',
            field=models.ManyToManyField(blank=True, related_name='events', to='cases.sourcedocument'),
        ),
    ]
