# Generated manually to match Django's autogenerated style (no local Django
# install available in this environment to run makemigrations — please run
# `python manage.py makemigrations --check` before applying in a real env).

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_remove_historicaltimelineevent_source_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=63, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='organization',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                related_name='profiles', to='cases.organization',
            ),
        ),
        # Nullable for now — backfilled in 0005, tightened to required in 0006.
        migrations.AddField(
            model_name='case',
            name='organization',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                related_name='cases', to='cases.organization',
            ),
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='organization',
            field=models.ForeignKey(
                blank=True, db_constraint=False, null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+', to='cases.organization',
            ),
        ),
    ]
