# Generated by Django 4.2.16 on 2026-09-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_profile_organization_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_real_ocr', models.BooleanField(blank=True, default=None, null=True)),
                ('use_real_llm', models.BooleanField(blank=True, default=None, null=True)),
                ('use_local_ocr', models.BooleanField(blank=True, default=None, null=True)),
                ('use_anthropic_llm', models.BooleanField(blank=True, default=None, null=True)),
                ('default_new_org_active', models.BooleanField(default=True)),
                ('default_new_member_role', models.CharField(choices=[('paralegal', 'Paralegal'), ('attorney', 'Attorney'), ('admin', 'Admin')], default='paralegal', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
